name: ci

on:
  push:
    branches:
      [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Log in to YC
        uses: docker/login-action@v1
        with:
          registry: cr.yandex
          username: oauth
          password: AQAAAABaGEJ0AATuwf6DfjCx8k0nib0fZyeMeGU
      -
         name: Build, tag, and push image to Yandex Cloud Container Registry
         run: |
          docker build -t cr.yandex/crpb9igt73ge599l10c1/lab1:latest .
          docker push cr.yandex/crpb9igt73ge599l10c1/lab1:latest
